### ISSUE TITLE
Question about teilchen functionality

### ISSUE THREAD

**Issue by Logenleedev** [dennisppaul/teilchen#7]
Just wondering does teilchen change object's shape, similar to [box2d](https://box2d.org/documentation/md__d_1__git_hub_box2d_docs_collision.html)? Right now, everything is particle (circle). Can we change it to polygon maybe?

**Comment by dennisppaul** [comment]
there is no concept of a shape in teilchen. it is really just particles and forces. however you can construct shape-like structures by connecting particles with e.g springs. see examples `Lesson06_StableQuads`, `Lesson08_Cloth` or `LessonX04_StickMan`.
